### ISSUE TITLE
Export at project level doesn't work

### ISSUE THREAD

**Issue by nroduit** [JMicroVision/jmicrovision#2]
Export Project as...
- Image
- Vector format

See https://jmicrovision.github.io/help/v1.3.1/user_interface/project_file_menu.htm

**Comment by Monacite-Nd** [comment]
Hi,
JMicrovision 1.3.1 during exporting project (Export project as…) gives an information “Process Interrupted: unidentified error during the process”. The problem is present on many computers with Windows 10 as well as Windows7. The issue doesn’t exist with JMicrovision 1.2.7 which works fine .
There is a reference to the new online help in previous massage, however I did not find any solution of this issue there . 
I attached 2 log files form different computers.

![JMicrovision_Bug](https://user-images.githubusercontent.com/56882247/67299994-9f62f580-f4ed-11e9-8f12-b2f509393b9b.jpg)

[Jmicrovision_logs_different_computers.zip](https://github.com/JMicroVision/jmicrovision/files/3756569/Jmicrovision_logs_different_computers.zip)

**Comment by nroduit** [comment]
Fix in 1.3.2
